stages:
  - test

test:
  stage: test
  image: python:3.9  # Specify the Python version you are using
  before_script:
    - pip install -r requirements.txt  # Install all dependencies
  script:
    - pytest  # Run pytest
